# Generated by Django 4.0.3 on 2022-03-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('seller_id', models.AutoField(primary_key=True, serialize=False)),
                ('seller_name', models.CharField(max_length=20)),
                ('email_id', models.CharField(max_length=30)),
                ('acc_holder', models.CharField(max_length=20)),
                ('acc_no', models.CharField(max_length=12)),
                ('ifsc', models.CharField(max_length=7)),
                ('phone_no', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'seller_tb',
            },
        ),
    ]
