# Generated by Django 4.0.3 on 2022-03-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_customer_table_alter_seller_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apiusers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'apiuser',
            },
        ),
    ]
